export interface IOptions {
  page?: string | number;
  pageSize?: string | number;
  pagesize?: string | number;
  pages?: string | number;
  noDenseRank?: boolean;
  noDistinct?: boolean;
  useRowNumber?: boolean;
  sort?: string;
  perDocumentLimit?: string;
  recursed?: string;
  tailable?: string;
  allowDiskUse?: string;
  batchSize?: string;
  readPreference?: string;
  hint?: string;
  comment?: string;
  snapshot?: string;
  maxscan?: string;
  upsert?: string;
  writeConcern?: string;
  timestamps?: string;
  overwriteDiscriminatorKey?: string;
  lean?: string;
  populate?: string;
  projection?: string;
  sanitizeProjection?: string;
  maxTimeMS?: string;
  rawResult?: string;
  strict?: string;
  collation?: string;
  session?: string;
  explain?: string;
}
