name: Publish

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test
    types:
     - completed
    branches:
      - main
      - master

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image: node:10.16-jessie

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: ARTIFACT TO UNZIP
        uses: judahh/artifactToUnzip@main
        with:
          production: true
      - name: Publish
        if: contains(matrix.node-version, '14.x')
        uses: judahh/npmPublish@main
        with:
          node_auth_token: ${{secrets.NODE_AUTH_TOKEN}}
